name: Flutter CI - run tests and analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: VitalCare

      - name: Analyze code
        run: flutter analyze
        working-directory: VitalCare

      - name: Run tests
        run: flutter test
        working-directory: VitalCare

